### ISSUE TITLE
Anyaggyűjtés

### ISSUE THREAD

**Issue by KristOOFF** [KristOOFF/nevezetessegek-feladat#1]
Legalább 7 nevezetességeket gyűjtsön mindenki egy nevezetessegek.txt(CSV) fájlba.

**Comment by GyulaBarnabas** [comment]
TEEEEEEEEEEEEEEEEEEEE

**Comment by GyulaBarnabas** [comment]
csinálj már egy fájl mert nem tudok addig forkolni

**Comment by GyulaBarnabas** [comment]
:(
