### ISSUE TITLE
Python kódolási feladatok kiosztása a csapattagok között

### ISSUE THREAD

**Issue by KristOOFF** [KristOOFF/nevezetessegek-feladat#2]
A menürendszer elkészítése: Unknown

A menüpontok:

1. nevezetességek listája

2. Országot választ a felhasználó, és a program kiírja az azon országokban lévő nevezetességek nevét

3. Várost választ a felhasználó, és a program kiírja a nevezetességek nevét és az ország nevét

**Comment by GyulaBarnabas** [comment]
éhes vagyok

**Comment by GyulaBarnabas** [comment]
what are the issues?
☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻☻
